# Site settings
title: Shakna Israel
description: "Design & Programming"
url: "http://www.shaknaisrael.com"
author:
  name: "James Milne"
  email: "contact@shaknaisrael.com"
  url: "http://www.shaknaisrael.com"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: false
reverse: false
